In [83]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.callbacks import EarlyStopping

In [84]:
data = pd.read_csv("pima-indians-diabetes.csv")

In [85]:
data

      6  148  72  35    0  33.6  0.627  50  1
0     1   85  66  29    0  26.6  0.351  31  0
1     8  183  64   0    0  23.3  0.672  32  1
2     1   89  66  23   94  28.1  0.167  21  0
3     0  137  40  35  168  43.1  2.288  33  1
4     5  116  74   0    0  25.6  0.201  30  0
..   ..  ...  ..  ..  ...   ...    ...  .. ..
762  10  101  76  48  180  32.9  0.171  63  0
763   2  122  70  27    0  36.8  0.340  27  0
764   5  121  72  23  112  26.2  0.245  30  0
765   1  126  60   0    0  30.1  0.349  47  1
766   1   93  70  31    0  30.4  0.315  23  0

[767 rows x 9 columns]

In [86]:
data.columns = [
    "Pregnancies",
    "Glucose",
    "BloodPressure",
    "SkinThickness",
    "Insulin",
    "BMI",
    "DiabetesPedigreeFunction",
    "Age",
    "Outcome"
]

data.head()

   Pregnancies  Glucose  BloodPressure  ...  DiabetesPedigreeFunction  Age  Outcome
0            1       85             66  ...                     0.351   31        0
1            8      183             64  ...                     0.672   32        1
2            1       89             66  ...                     0.167   21        0
3            0      137             40  ...                     2.288   33        1
4            5      116             74  ...                     0.201   30        0

[5 rows x 9 columns]

In [87]:
X = data.drop("Outcome", axis=1)
y = data["Outcome"]

In [88]:
data.isnull().sum()

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [89]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

In [90]:
scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [91]:
model = Sequential([
    Dense(32, activation="relu", input_shape=(X_train.shape[1],)),
    Dense(16, activation="relu"),
    Dense(1, activation="sigmoid")
])

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [92]:
model.compile(optimizer=Adam(learning_rate=0.001), loss='binary_crossentropy', metrics=['accuracy'])

early_stop = EarlyStopping(
    monitor="val_loss",
    patience=10,
    restore_best_weights=True
)
history = model.fit(
    X_train,
    y_train,
    epochs=100,
    batch_size=16,
    validation_split=0.2,
    callbacks=[early_stop],
    verbose=1
)

Epoch 1/100
31/31 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - accuracy: 0.4123 - loss: 0.7921 - val_accuracy: 0.5854 - val_loss: 0.6609
Epoch 2/100
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6414 - loss: 0.6534 - val_accuracy: 0.7317 - val_loss: 0.5959
Epoch 3/100
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7399 - loss: 0.5822 - val_accuracy: 0.7480 - val_loss: 0.5539
Epoch 4/100
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7616 - loss: 0.5271 - val_accuracy: 0.7642 - val_loss: 0.5230
Epoch 5/100
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8341 - loss: 0.4678 - val_accuracy: 0.7480 - val_loss: 0.5027
Epoch 6/100
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7884 - loss: 0.4872 - val_accuracy: 0.7561 - val_loss: 0.4937
Epoch 7/100
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7780 - loss: 0.4594 - val_accuracy: 0.7480 - val_loss: 0.4835
Epoch 8/100
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7966 - loss: 0.4469 - val_accuracy: 0.7480 - val_loss: 0.4797
Epoch 9/100
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8194 - loss: 0.4342 - val_accuracy: 0.7642 - val_loss: 0.4789
Epoch 10/100
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8330 - loss: 0.4236 - val_accuracy: 0.7642 - val_loss: 0.4764
Epoch 11/100
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8222 - loss: 0.4384 - val_accuracy: 0.7642 - val_loss: 0.4760
Epoch 12/100
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8182 - loss: 0.4365 - val_accuracy: 0.7642 - val_loss: 0.4706
Epoch 13/100
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8071 - loss: 0.4561 - val_accuracy: 0.7642 - val_loss: 0.4754
Epoch 14/100
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8090 - loss: 0.4250 - val_accuracy: 0.7642 - val_loss: 0.4715
Epoch 15/100
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8255 - loss: 0.4056 - val_accuracy: 0.7561 - val_loss: 0.4712
Epoch 16/100
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8011 - loss: 0.4471 - val_accuracy: 0.7642 - val_loss: 0.4695
Epoch 17/100
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8076 - loss: 0.4179 - val_accuracy: 0.7642 - val_loss: 0.4687
Epoch 18/100
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8045 - loss: 0.4194 - val_accuracy: 0.7642 - val_loss: 0.4662
Epoch 19/100
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8132 - loss: 0.4169 - val_accuracy: 0.7642 - val_loss: 0.4711
Epoch 20/100
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8393 - loss: 0.3976 - val_accuracy: 0.7642 - val_loss: 0.4659
Epoch 21/100
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8394 - loss: 0.3825 - val_accuracy: 0.7561 - val_loss: 0.4682
Epoch 22/100
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8247 - loss: 0.3906 - val_accuracy: 0.7724 - val_loss: 0.4727
Epoch 23/100
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8345 - loss: 0.3886 - val_accuracy: 0.7724 - val_loss: 0.4694
Epoch 24/100
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8435 - loss: 0.3705 - val_accuracy: 0.7642 - val_loss: 0.4638
Epoch 25/100
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8359 - loss: 0.3797 - val_accuracy: 0.7642 - val_loss: 0.4648
Epoch 26/100
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8230 - loss: 0.3940 - val_accuracy: 0.7642 - val_loss: 0.4680
Epoch 27/100
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7814 - loss: 0.4565 - val_accuracy: 0.7805 - val_loss: 0.4654
Epoch 28/100
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8334 - loss: 0.3823 - val_accuracy: 0.7642 - val_loss: 0.4654
Epoch 29/100
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8174 - loss: 0.4075 - val_accuracy: 0.7724 - val_loss: 0.4661
Epoch 30/100
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8099 - loss: 0.4187 - val_accuracy: 0.7642 - val_loss: 0.4645
Epoch 31/100
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8584 - loss: 0.3578 - val_accuracy: 0.7724 - val_loss: 0.4658
Epoch 32/100
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8459 - loss: 0.3758 - val_accuracy: 0.7724 - val_loss: 0.4671
Epoch 33/100
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8311 - loss: 0.3867 - val_accuracy: 0.7642 - val_loss: 0.4611
Epoch 34/100
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8339 - loss: 0.3779 - val_accuracy: 0.7724 - val_loss: 0.4600
Epoch 35/100
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8376 - loss: 0.3870 - val_accuracy: 0.7724 - val_loss: 0.4631
Epoch 36/100
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8392 - loss: 0.3838 - val_accuracy: 0.7642 - val_loss: 0.4602
Epoch 37/100
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8275 - loss: 0.3826 - val_accuracy: 0.7724 - val_loss: 0.4608
Epoch 38/100
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8391 - loss: 0.3711 - val_accuracy: 0.7724 - val_loss: 0.4621
Epoch 39/100
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8477 - loss: 0.3739 - val_accuracy: 0.7724 - val_loss: 0.4610
Epoch 40/100
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8365 - loss: 0.3840 - val_accuracy: 0.7724 - val_loss: 0.4609
Epoch 41/100
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8476 - loss: 0.3578 - val_accuracy: 0.7805 - val_loss: 0.4586
Epoch 42/100
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8155 - loss: 0.3973 - val_accuracy: 0.7805 - val_loss: 0.4557
Epoch 43/100
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8097 - loss: 0.4198 - val_accuracy: 0.7805 - val_loss: 0.4614
Epoch 44/100
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8748 - loss: 0.3204 - val_accuracy: 0.7805 - val_loss: 0.4618
Epoch 45/100
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8555 - loss: 0.3294 - val_accuracy: 0.7805 - val_loss: 0.4569
Epoch 46/100
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8621 - loss: 0.3409 - val_accuracy: 0.7886 - val_loss: 0.4539
Epoch 47/100
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8572 - loss: 0.3522 - val_accuracy: 0.7886 - val_loss: 0.4599
Epoch 48/100
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8462 - loss: 0.3541 - val_accuracy: 0.7967 - val_loss: 0.4535
Epoch 49/100
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8484 - loss: 0.3618 - val_accuracy: 0.7886 - val_loss: 0.4614
Epoch 50/100
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8486 - loss: 0.3703 - val_accuracy: 0.7805 - val_loss: 0.4566
Epoch 51/100
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8594 - loss: 0.3337 - val_accuracy: 0.7886 - val_loss: 0.4574
Epoch 52/100
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8466 - loss: 0.3967 - val_accuracy: 0.7805 - val_loss: 0.4583
Epoch 53/100
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8507 - loss: 0.3620 - val_accuracy: 0.7967 - val_loss: 0.4556
Epoch 54/100
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8680 - loss: 0.3385 - val_accuracy: 0.7805 - val_loss: 0.4560
Epoch 55/100
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8721 - loss: 0.3317 - val_accuracy: 0.7886 - val_loss: 0.4561
Epoch 56/100
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8437 - loss: 0.3406 - val_accuracy: 0.7805 - val_loss: 0.4569
Epoch 57/100
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8623 - loss: 0.3396 - val_accuracy: 0.7967 - val_loss: 0.4519
Epoch 58/100
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8484 - loss: 0.3267 - val_accuracy: 0.7886 - val_loss: 0.4506
Epoch 59/100
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8780 - loss: 0.3077 - val_accuracy: 0.7805 - val_loss: 0.4610
Epoch 60/100
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8502 - loss: 0.3625 - val_accuracy: 0.7886 - val_loss: 0.4488
Epoch 61/100
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8527 - loss: 0.3246 - val_accuracy: 0.7886 - val_loss: 0.4603
Epoch 62/100
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8404 - loss: 0.3352 - val_accuracy: 0.7886 - val_loss: 0.4560
Epoch 63/100
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8483 - loss: 0.3533 - val_accuracy: 0.7886 - val_loss: 0.4563
Epoch 64/100
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8589 - loss: 0.3265 - val_accuracy: 0.7886 - val_loss: 0.4564
Epoch 65/100
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8478 - loss: 0.3380 - val_accuracy: 0.7967 - val_loss: 0.4575
Epoch 66/100
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8471 - loss: 0.3479 - val_accuracy: 0.7967 - val_loss: 0.4598
Epoch 67/100
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8299 - loss: 0.3578 - val_accuracy: 0.7967 - val_loss: 0.4545
Epoch 68/100
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8398 - loss: 0.3488 - val_accuracy: 0.7967 - val_loss: 0.4579
Epoch 69/100
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8526 - loss: 0.3244 - val_accuracy: 0.7886 - val_loss: 0.4603
Epoch 70/100
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8477 - loss: 0.3502 - val_accuracy: 0.7805 - val_loss: 0.4576

In [93]:
loss, accuracy = model.evaluate(X_test, y_test)
print("Test Accuracy:", accuracy * 100)

5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7242 - loss: 0.5859
Test Accuracy: 70.77922224998474

In [82]:
import os
print(os.listdir('.'))

['.config', 'FNN_classification.ipynb', 'pima-indians-diabetes.csv', 'sample_data']

In [94]:

y_pred_prob = model.predict(X_test)
y_pred = (y_pred_prob >= 0.5).astype(int)

5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step

In [95]:

from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:\n", cm)

Confusion Matrix:
 [[81 19]
 [26 28]]

In [96]:

from sklearn.metrics import classification_report

print("Classification Report:\n")
print(classification_report(y_test, y_pred))

Classification Report:

              precision    recall  f1-score   support

           0       0.76      0.81      0.78       100
           1       0.60      0.52      0.55        54

    accuracy                           0.71       154
   macro avg       0.68      0.66      0.67       154
weighted avg       0.70      0.71      0.70       154